version: "3"
services:
    frontend: 
        build: 
            context: ./my-app
            dockerfile: Dockerfile.dev
        # restart: unless-stopped
        ports: 
            - "80:3000"
        volumes: 
            - ./my-app:/app
            - /app/node_modules
        environment:
            CHOKIDAR_USEPOLLING: "true"
    backend:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        # restart: unless-stopped
        ports:
            - "8080:8080"
        volumes: 
            - ./server/src:/app/src
            # - /app/node_modules
    database: 
        image: mysql:latest
        restart: unless-stopped
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=password
        volumes: 
            - os-iot-database:/var/lib/mysql

volumes: 
    os-iot-database: